# ===================================================================
# ATA Backend - Full Database Reset and Migration Script (PowerShell)
# ===================================================================
#
# This script:
# 1. Drops and recreates the database
# 2. Deletes old migrations
# 3. Generates fresh migration from models
# 4. Fixes table ordering automatically
# 5. Applies migrations
# 6. Verifies database setup
#
# Usage: .\reset_and_migrate.ps1
# ===================================================================

Write-Host ""
Write-Host "===================================================================" -ForegroundColor Cyan
Write-Host "ATA Backend - Database Reset and Migration" -ForegroundColor Cyan
Write-Host "===================================================================" -ForegroundColor Cyan
Write-Host ""

# Function to check if command succeeded
function Test-LastCommand {
    param([string]$ErrorMessage)
    if ($LASTEXITCODE -ne 0) {
        Write-Host "ERROR: $ErrorMessage" -ForegroundColor Red
        Read-Host "Press Enter to exit"
        exit 1
    }
}

# Step 1: Drop existing database
Write-Host "[1/7] Dropping existing database..." -ForegroundColor Yellow
psql "postgresql://ata_user:ata_password@localhost:5432/postgres" -c "DROP DATABASE IF EXISTS ata_local_db;"
Test-LastCommand "Failed to drop database. Make sure PostgreSQL is running."
Write-Host "      Done!" -ForegroundColor Green
Write-Host ""

# Step 2: Create fresh database
Write-Host "[2/7] Creating fresh database..." -ForegroundColor Yellow
psql "postgresql://ata_user:ata_password@localhost:5432/postgres" -c "CREATE DATABASE ata_local_db;"
Test-LastCommand "Failed to create database"
Write-Host "      Done!" -ForegroundColor Green
Write-Host ""

# Step 3: Delete old migrations
Write-Host "[3/7] Deleting old migration files..." -ForegroundColor Yellow
Remove-Item -Path "alembic\versions\*.py" -Force -ErrorAction SilentlyContinue
"" | Out-File -FilePath "alembic\versions\__init__.py" -Encoding ASCII
Write-Host "      Done!" -ForegroundColor Green
Write-Host ""

# Step 4: Activate virtual environment
Write-Host "[4/7] Activating virtual environment..." -ForegroundColor Yellow
if (Test-Path "venv\Scripts\Activate.ps1") {
    & "venv\Scripts\Activate.ps1"
} else {
    Write-Host "ERROR: Virtual environment not found" -ForegroundColor Red
    Write-Host "Create it with: python -m venv venv" -ForegroundColor Yellow
    Read-Host "Press Enter to exit"
    exit 1
}
Write-Host "      Done!" -ForegroundColor Green
Write-Host ""

# Step 5: Generate fresh migration
Write-Host "[5/7] Generating fresh migration from models..." -ForegroundColor Yellow
alembic revision --autogenerate -m "Initial database schema"
Test-LastCommand "Failed to generate migration. Make sure Alembic is installed."
Write-Host "      Done!" -ForegroundColor Green
Write-Host ""

# Step 6: Fix migration table ordering
Write-Host "[6/7] Fixing migration table ordering..." -ForegroundColor Yellow
python fix_autogenerated_migration.py
Test-LastCommand "Failed to fix migration"
Write-Host "      Done!" -ForegroundColor Green
Write-Host ""

# Step 7: Apply migrations
Write-Host "[7/7] Applying migrations to database..." -ForegroundColor Yellow
alembic upgrade head
Test-LastCommand "Failed to apply migrations"
Write-Host "      Done!" -ForegroundColor Green
Write-Host ""

# Verification
Write-Host "===================================================================" -ForegroundColor Cyan
Write-Host "Verifying database setup..." -ForegroundColor Cyan
Write-Host "===================================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Database tables:" -ForegroundColor Yellow
psql "postgresql://ata_user:ata_password@localhost:5432/ata_local_db" -c "\dt"
Write-Host ""

Write-Host "===================================================================" -ForegroundColor Green
Write-Host "SUCCESS! Database is ready." -ForegroundColor Green
Write-Host "===================================================================" -ForegroundColor Green
Write-Host ""
Write-Host "You can now start the backend:" -ForegroundColor Yellow
Write-Host "   uvicorn app.main:app --reload --host 0.0.0.0 --env-file .env" -ForegroundColor Cyan
Write-Host ""

$response = Read-Host "Start backend now? (Y/n)"
if ($response -eq "" -or $response -eq "Y" -or $response -eq "y") {
    Write-Host ""
    Write-Host "Starting backend server..." -ForegroundColor Yellow
    uvicorn app.main:app --reload --host 0.0.0.0 --env-file .env
}
