@echo off
REM ===================================================================
REM ATA Backend - Full Database Reset and Migration Script
REM ===================================================================
REM
REM This script:
REM 1. Drops and recreates the database
REM 2. Deletes old migrations
REM 3. Generates fresh migration from models
REM 4. Fixes table ordering automatically
REM 5. Applies migrations
REM 6. Verifies database setup
REM
REM Usage: Run this script from ata-backend directory
REM ===================================================================

echo.
echo ===================================================================
echo ATA Backend - Database Reset and Migration
echo ===================================================================
echo.

REM Step 1: Drop existing database
echo [1/7] Dropping existing database...
psql "postgresql://ata_user:ata_password@localhost:5432/postgres" -c "DROP DATABASE IF EXISTS ata_local_db;"
if %ERRORLEVEL% NEQ 0 (
    echo ERROR: Failed to drop database
    echo Make sure PostgreSQL is running and credentials are correct
    pause
    exit /b 1
)
echo       Done!
echo.

REM Step 2: Create fresh database
echo [2/7] Creating fresh database...
psql "postgresql://ata_user:ata_password@localhost:5432/postgres" -c "CREATE DATABASE ata_local_db;"
if %ERRORLEVEL% NEQ 0 (
    echo ERROR: Failed to create database
    pause
    exit /b 1
)
echo       Done!
echo.

REM Step 3: Delete old migrations
echo [3/7] Deleting old migration files...
del /Q alembic\versions\*.py 2>nul
echo. > alembic\versions\__init__.py
echo       Done!
echo.

REM Step 4: Activate virtual environment
echo [4/7] Activating virtual environment...
call venv\Scripts\activate
if %ERRORLEVEL% NEQ 0 (
    echo ERROR: Failed to activate virtual environment
    echo Make sure venv exists (run: python -m venv venv)
    pause
    exit /b 1
)
echo       Done!
echo.

REM Step 5: Generate fresh migration
echo [5/7] Generating fresh migration from models...
alembic revision --autogenerate -m "Initial database schema"
if %ERRORLEVEL% NEQ 0 (
    echo ERROR: Failed to generate migration
    echo Make sure Alembic is installed (run: pip install alembic)
    pause
    exit /b 1
)
echo       Done!
echo.

REM Step 6: Fix migration table ordering
echo [6/7] Fixing migration table ordering...
python fix_autogenerated_migration.py
if %ERRORLEVEL% NEQ 0 (
    echo ERROR: Failed to fix migration
    echo Check fix_autogenerated_migration.py output above
    pause
    exit /b 1
)
echo       Done!
echo.

REM Step 7: Apply migrations
echo [7/7] Applying migrations to database...
alembic upgrade head
if %ERRORLEVEL% NEQ 0 (
    echo ERROR: Failed to apply migrations
    echo Check error message above
    pause
    exit /b 1
)
echo       Done!
echo.

REM Verification
echo ===================================================================
echo Verifying database setup...
echo ===================================================================
echo.
echo Database tables:
psql "postgresql://ata_user:ata_password@localhost:5432/ata_local_db" -c "\dt"
echo.

echo ===================================================================
echo SUCCESS! Database is ready.
echo ===================================================================
echo.
echo You can now start the backend:
echo    uvicorn app.main:app --reload --host 0.0.0.0 --env-file .env
echo.
echo Or press any key to start it now...
pause >nul

REM Start backend
echo.
echo Starting backend server...
uvicorn app.main:app --reload --host 0.0.0.0 --env-file .env
