"""Initial database schema

Revision ID: 39b5da5d9e02
Revises: 
Create Date: 2025-11-14 21:21:45.290114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39b5da5d9e02'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('studentId', sa.String(), nullable=False),
    sa.Column('overallGrade', sa.Integer(), nullable=True),
    sa.Column('performance_summary', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_name'), 'students', ['name'], unique=False)
    op.create_index(op.f('ix_students_studentId'), 'students', ['studentId'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('answer_sheet_paths', sa.JSON(), nullable=True),
    sa.Column('ai_summary', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('total_pages', sa.Float(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_id'), 'assessments', ['id'], unique=False)
    op.create_index(op.f('ix_assessments_status'), 'assessments', ['status'], unique=False)
    op.create_index(op.f('ix_assessments_user_id'), 'assessments', ['user_id'], unique=False)
    op.create_table('chatsessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatsessions_id'), 'chatsessions', ['id'], unique=False)
    op.create_index(op.f('ix_chatsessions_user_id'), 'chatsessions', ['user_id'], unique=False)
    op.create_table('classes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_id'), 'classes', ['id'], unique=False)
    op.create_index(op.f('ix_classes_name'), 'classes', ['name'], unique=False)
    op.create_index(op.f('ix_classes_user_id'), 'classes', ['user_id'], unique=False)
    op.create_table('generations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('tool_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('settings_snapshot', sa.JSON(), nullable=False),
    sa.Column('generated_content', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generations_id'), 'generations', ['id'], unique=False)
    op.create_index(op.f('ix_generations_tool_id'), 'generations', ['tool_id'], unique=False)
    op.create_index(op.f('ix_generations_user_id'), 'generations', ['user_id'], unique=False)
    op.create_table('chatmessages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chatsessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatmessages_id'), 'chatmessages', ['id'], unique=False)
    op.create_table('outsider_students',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outsider_students_assessment_id'), 'outsider_students', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_outsider_students_name'), 'outsider_students', ['name'], unique=False)
    op.create_table('quizzes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_room_code', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quizzes_class_not_deleted', 'quizzes', ['class_id'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_quizzes_user_status_not_deleted', 'quizzes', ['user_id', 'status'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_quizzes_class_id'), 'quizzes', ['class_id'], unique=False)
    op.create_index(op.f('ix_quizzes_last_room_code'), 'quizzes', ['last_room_code'], unique=False)
    op.create_index(op.f('ix_quizzes_status'), 'quizzes', ['status'], unique=False)
    op.create_index(op.f('ix_quizzes_title'), 'quizzes', ['title'], unique=False)
    op.create_index(op.f('ix_quizzes_user_id'), 'quizzes', ['user_id'], unique=False)
    op.create_table('student_class_memberships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('class_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'class_id', name='uq_student_class')
    )
    op.create_index(op.f('ix_student_class_memberships_class_id'), 'student_class_memberships', ['class_id'], unique=False)
    op.create_index(op.f('ix_student_class_memberships_id'), 'student_class_memberships', ['id'], unique=False)
    op.create_index(op.f('ix_student_class_memberships_student_id'), 'student_class_memberships', ['student_id'], unique=False)
    op.create_table('ai_model_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('outsider_student_id', sa.String(), nullable=True),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('run_index', sa.SmallInteger(), nullable=False),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('grade', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(student_id IS NOT NULL AND outsider_student_id IS NULL) OR (student_id IS NULL AND outsider_student_id IS NOT NULL)', name='chk_aimodelrun_student_or_outsider'),
    sa.ForeignKeyConstraint(['job_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outsider_student_id'], ['outsider_students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'outsider_student_id', 'question_id', 'run_index', name='_job_outsider_question_run_uc'),
    sa.UniqueConstraint('job_id', 'student_id', 'question_id', 'run_index', name='_job_student_question_run_uc')
    )
    op.create_index(op.f('ix_ai_model_runs_job_id'), 'ai_model_runs', ['job_id'], unique=False)
    op.create_index(op.f('ix_ai_model_runs_outsider_student_id'), 'ai_model_runs', ['outsider_student_id'], unique=False)
    op.create_index(op.f('ix_ai_model_runs_question_id'), 'ai_model_runs', ['question_id'], unique=False)
    op.create_index(op.f('ix_ai_model_runs_student_id'), 'ai_model_runs', ['student_id'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('quiz_id', sa.String(), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('correct_answer', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('media_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quiz_questions_quiz_order', 'quiz_questions', ['quiz_id', 'order_index'], unique=False)
    op.create_index(op.f('ix_quiz_questions_question_type'), 'quiz_questions', ['question_type'], unique=False)
    op.create_index(op.f('ix_quiz_questions_quiz_id'), 'quiz_questions', ['quiz_id'], unique=False)
    op.create_table('quiz_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('quiz_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('room_code', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_question_index', sa.Integer(), nullable=True),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('timeout_hours', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('question_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quiz_sessions_status_created', 'quiz_sessions', ['status', 'created_at'], unique=False)
    op.create_index('idx_quiz_sessions_user_status', 'quiz_sessions', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_quiz_sessions_quiz_id'), 'quiz_sessions', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_sessions_room_code'), 'quiz_sessions', ['room_code'], unique=True)
    op.create_index(op.f('ix_quiz_sessions_status'), 'quiz_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_quiz_sessions_user_id'), 'quiz_sessions', ['user_id'], unique=False)
    op.create_table('results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('outsider_student_id', sa.String(), nullable=True),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.Column('feedback', sa.String(), nullable=True),
    sa.Column('extractedAnswer', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('report_token', sa.String(), nullable=True),
    sa.Column('answer_sheet_path', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('finalized_by', sa.Enum('AI', 'TEACHER', name='finalizedby'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_responses', sa.JSON(), nullable=True),
    sa.CheckConstraint('(student_id IS NOT NULL AND outsider_student_id IS NULL) OR (student_id IS NULL AND outsider_student_id IS NOT NULL)', name='chk_result_student_or_outsider'),
    sa.ForeignKeyConstraint(['job_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['outsider_student_id'], ['outsider_students.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_results_id'), 'results', ['id'], unique=False)
    op.create_index(op.f('ix_results_report_token'), 'results', ['report_token'], unique=True)
    op.create_table('quiz_participants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('guest_name', sa.String(length=50), nullable=True),
    sa.Column('guest_token', sa.String(length=64), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('total_time_ms', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('anonymized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(student_id IS NOT NULL AND guest_name IS NULL AND guest_token IS NULL) OR (student_id IS NULL AND guest_name IS NOT NULL AND guest_token IS NOT NULL) OR (student_id IS NOT NULL AND guest_name IS NOT NULL AND guest_token IS NOT NULL)', name='chk_participant_identity'),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_participants_gdpr_cleanup', 'quiz_participants', ['joined_at', 'anonymized_at'], unique=False, postgresql_where=sa.text('guest_token IS NOT NULL'))
    op.create_index('idx_participants_session_active', 'quiz_participants', ['session_id', 'is_active'], unique=False)
    op.create_index('idx_participants_session_score', 'quiz_participants', ['session_id', sa.literal_column('score DESC')], unique=False)
    op.create_index(op.f('ix_quiz_participants_guest_token'), 'quiz_participants', ['guest_token'], unique=True)
    op.create_index(op.f('ix_quiz_participants_session_id'), 'quiz_participants', ['session_id'], unique=False)
    op.create_index(op.f('ix_quiz_participants_student_id'), 'quiz_participants', ['student_id'], unique=False)
    op.create_table('quiz_responses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('participant_id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('answer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.Column('time_taken_ms', sa.Integer(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['quiz_participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'participant_id', 'question_id', name='uq_one_answer_per_participant_question')
    )
    op.create_index('idx_responses_leaderboard', 'quiz_responses', ['session_id', 'is_correct', 'points_earned'], unique=False)
    op.create_index('idx_responses_question_analytics', 'quiz_responses', ['question_id', 'is_correct', 'time_taken_ms'], unique=False)
    op.create_index(op.f('ix_quiz_responses_participant_id'), 'quiz_responses', ['participant_id'], unique=False)
    op.create_index(op.f('ix_quiz_responses_question_id'), 'quiz_responses', ['question_id'], unique=False)
    op.create_index(op.f('ix_quiz_responses_session_id'), 'quiz_responses', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_responses_session_id'), table_name='quiz_responses')
    op.drop_index(op.f('ix_quiz_responses_question_id'), table_name='quiz_responses')
    op.drop_index(op.f('ix_quiz_responses_participant_id'), table_name='quiz_responses')
    op.drop_index('idx_responses_question_analytics', table_name='quiz_responses')
    op.drop_index('idx_responses_leaderboard', table_name='quiz_responses')
    op.drop_table('quiz_responses')
    op.drop_index(op.f('ix_quiz_participants_student_id'), table_name='quiz_participants')
    op.drop_index(op.f('ix_quiz_participants_session_id'), table_name='quiz_participants')
    op.drop_index(op.f('ix_quiz_participants_guest_token'), table_name='quiz_participants')
    op.drop_index('idx_participants_session_score', table_name='quiz_participants')
    op.drop_index('idx_participants_session_active', table_name='quiz_participants')
    op.drop_index('idx_participants_gdpr_cleanup', table_name='quiz_participants', postgresql_where=sa.text('guest_token IS NOT NULL'))
    op.drop_table('quiz_participants')
    op.drop_index(op.f('ix_results_report_token'), table_name='results')
    op.drop_index(op.f('ix_results_id'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_quiz_sessions_user_id'), table_name='quiz_sessions')
    op.drop_index(op.f('ix_quiz_sessions_status'), table_name='quiz_sessions')
    op.drop_index(op.f('ix_quiz_sessions_room_code'), table_name='quiz_sessions')
    op.drop_index(op.f('ix_quiz_sessions_quiz_id'), table_name='quiz_sessions')
    op.drop_index('idx_quiz_sessions_user_status', table_name='quiz_sessions')
    op.drop_index('idx_quiz_sessions_status_created', table_name='quiz_sessions')
    op.drop_table('quiz_sessions')
    op.drop_index(op.f('ix_quiz_questions_quiz_id'), table_name='quiz_questions')
    op.drop_index(op.f('ix_quiz_questions_question_type'), table_name='quiz_questions')
    op.drop_index('idx_quiz_questions_quiz_order', table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index(op.f('ix_ai_model_runs_student_id'), table_name='ai_model_runs')
    op.drop_index(op.f('ix_ai_model_runs_question_id'), table_name='ai_model_runs')
    op.drop_index(op.f('ix_ai_model_runs_outsider_student_id'), table_name='ai_model_runs')
    op.drop_index(op.f('ix_ai_model_runs_job_id'), table_name='ai_model_runs')
    op.drop_table('ai_model_runs')
    op.drop_index(op.f('ix_student_class_memberships_student_id'), table_name='student_class_memberships')
    op.drop_index(op.f('ix_student_class_memberships_id'), table_name='student_class_memberships')
    op.drop_index(op.f('ix_student_class_memberships_class_id'), table_name='student_class_memberships')
    op.drop_table('student_class_memberships')
    op.drop_index(op.f('ix_quizzes_user_id'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_title'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_status'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_last_room_code'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_class_id'), table_name='quizzes')
    op.drop_index('idx_quizzes_user_status_not_deleted', table_name='quizzes', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_quizzes_class_not_deleted', table_name='quizzes', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('quizzes')
    op.drop_index(op.f('ix_outsider_students_name'), table_name='outsider_students')
    op.drop_index(op.f('ix_outsider_students_assessment_id'), table_name='outsider_students')
    op.drop_table('outsider_students')
    op.drop_index(op.f('ix_chatmessages_id'), table_name='chatmessages')
    op.drop_table('chatmessages')
    op.drop_index(op.f('ix_generations_user_id'), table_name='generations')
    op.drop_index(op.f('ix_generations_tool_id'), table_name='generations')
    op.drop_index(op.f('ix_generations_id'), table_name='generations')
    op.drop_table('generations')
    op.drop_index(op.f('ix_classes_user_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_name'), table_name='classes')
    op.drop_index(op.f('ix_classes_id'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_chatsessions_user_id'), table_name='chatsessions')
    op.drop_index(op.f('ix_chatsessions_id'), table_name='chatsessions')
    op.drop_table('chatsessions')
    op.drop_index(op.f('ix_assessments_user_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_status'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_students_studentId'), table_name='students')
    op.drop_index(op.f('ix_students_name'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
